services:
  geth-peer:
    image: ethereum/client-go:v1.13.15
    container_name: geth-peer
    network_mode: host
    volumes:
      - ./data2:/root/.ethereum
      - ./genesis.json:/genesis.json
      - ./password-peer.txt:/root/.ethereum/password.txt
    command:
      - --datadir=/root/.ethereum
      - --networkid=1337
      - --http
      - --http.addr=0.0.0.0
      - --http.port=8547
      - --http.api=eth,net,web3,personal,miner,admin
      - --http.corsdomain=*
      - --http.vhosts=*
      - --ws
      - --ws.addr=0.0.0.0
      - --ws.port=8548
      - --ws.api=eth,net,web3,personal,miner,admin
      - --ws.origins=*
      - --allow-insecure-unlock
      - --unlock=0x71c8e1e88ec498f1575758d0b1370186fe8781f7
      - --password=/root/.ethereum/password.txt
      - --bootnodes=enode://12ddd02d53f95e6f6f475e850b950a5b8bce674cd0f43fd928d53e986d974b02b7be91521509befccb971214dfb765d4a1833f307252a9aa8021db0ae86c5a78@172.16.103.6:30303
      - --port=30304
    stdin_open: true
    tty: true
    restart: unless-stopped
